### PR TITLE
fix(optimizer): fix logical scan pk derive

### LINKED ISSUE #3086: invalid flush status: double insert
**Describe the bug**

```
thread 'tokio-runtime-worker' panicked at 'invalid flush status: double insert (Some("006f52e9102a8d3be2fe5614f42ba989"), []) -> Some(Utf8("006f52e9102a8d3be2fe5614f42ba989"))', src/stream/src/executor/managed_state/flush_status.rs:119:1
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

It is reproducible but the testing steps might be a little complicated.

1. Load a lot of data into risingwave.
2. Run SQL:

```sql
create materialized view TcpJoinUtilMetrics as 
select 
  tcp.DeviceId as DeviceId, 
  tcp.window_end as window_end, 
  tcp.MetricName, 
  tcp.MetricValue 
from 
  (
    select 
      DeviceId, 
      window_end, 
      MetricName, 
      avg(Value) as MetricValue 
    from 
      HOP(
        MonTcpMetrics, ReportTime, INTERVAL '1' MINUTE, 
        INTERVAL '10' MINUTE
      ) 
    where 
      Domain = 'all' 
    group by 
      DeviceId, 
      window_end, 
      MetricName
  ) as tcp 
  join (
    select 
      DeviceId, 
      window_end, 
      avg(
        (Value * 8 / 10) / LinkBandwidth
      ) as AvgUtil 
    from 
      HOP(
        MonNicsMetrics, ReportTime, INTERVAL '1' MINUTE, 
        INTERVAL '10' MINUTE
      ) 
    where 
      MetricName = 'tx_bytes' 
      and Aggregation = 'avg' 
    group by 
      DeviceId, 
      window_end
  ) as nic on tcp.DeviceId = nic.DeviceId 
  and tcp.window_end = nic.window_end 
where 
  AvgUtil >= 50;
```

```sql
create materialized view mv as
select
    max(DeviceId) as DeviceId,
    max(MetricValue) as retrans,
from
    TcpJoinUtilMetrics
where
    MetricName = 'retrans_rate';
```

The second SQL will panic. I will try to narrow down the error scope. Eventually, it should be reproducible in a relatively simpler e2e test.

**Additional context**

### PR DESCRIPTION
**Pull request by st1page**
## What's changed and what's your intention?
revert #3119 
fix #3086,  #3118 

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/logical_project.rs [hunk 1]
```diff
@@ -132,8 +132,9 @@ impl LogicalProject {
         let i2o = Self::i2o_col_mapping_inner(input_schema.len(), exprs);
         input_pk
             .iter()
-            .filter_map(|pk_col| i2o.try_map(*pk_col))
-            .collect::<Vec<_>>()
+            .map(|pk_col| i2o.try_map(*pk_col))
+            .collect::<Option<Vec<_>>>()
+            .unwrap_or_default()
```
Comment (skyzh) [inline src/frontend/src/optimizer/plan_node/logical_project.rs:137]: .expect("pk lost during optimization") instead of returning an empty pk set?

**Review by skyzh — APPROVED** [review]

File: src/frontend/src/optimizer/plan_node/logical_project.rs (hunk 1 above)
Comment (st1page) [reply src/frontend/src/optimizer/plan_node/logical_project.rs:137]: the batch query does not need the pk... I am thinking if we can move the pk property only in stream plan node.
