### PR TITLE
fix(meta): fix missing source info during `CREATE MATERIALIZED SOURCE`

### LINKED ISSUE #1808: bug: Cannot create materialized source
**Describe the bug**
CREATE MATERIALIZED SOURCE fails with and internal error.

**To Reproduce**
```
patrick=> create materialized source kafka2 (v1 int, v2 varchar) with ('connector'='kafka', 'kafka.topic'='kafka_1_partition_mv_topic', 'kafka.broker'='127.0.0.1:29092', 'kafka.scan.startup.mode'='earliest', 'kafka.consumer.group'='kafka1-c2') ROW FORMAT JSON;
ERROR:  internal error: internal error: could not find source catalog for 2000
```

**Expected behavior**
CREATE MATERIALIZED SOURCE should succeed

**Additional context**

### PR DESCRIPTION
**Pull request by zbzbw**
Signed-off-by: Bowen Zhou <bowenzhou@singularity-data.com>

## What's changed and what's your intention?

As title. To maintain consistency of creating materialized source, we only write catalog after both source and mview have been created. But:

> create materialized source = create source + create mview
> 
> Root cause: we only update catalog after both source and mview creation succeed but in the current implementation mview creation requires the source to exist in catalog
> 
> https://github.com/singularity-data/risingwave/blob/62aba2a41cff3c84608266170510dd56b9906761/src/meta/src/rpc/service/ddl_service.rs#L499
> 
> https://github.com/singularity-data/risingwave/blob/62aba2a41cff3c84608266170510dd56b9906761/src/meta/src/stream/source_manager.rs#L66

Now we will pass the source info into `create_materialized_view`'s context during `CREATE MATERIALIZED SOURCE`.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

Fix #1808.

### CODE REVIEW

File: src/meta/src/stream/source_manager.rs [hunk 1]
```diff
@@ -93,12 +85,29 @@ where
...
+        affiliated_source: Option<Source>,
     ) -> Result<HashMap<ActorId, Vec<SplitImpl>>> {
-        let source_splits = try_join_all(
-            actors
-                .keys()
-                .map(|source_id| self.fetch_splits_for_source(*source_id)),
-        )
+        let source_ref = &affiliated_source;
+        let source_splits = try_join_all(actors.keys().map(|source_id| async move {
+            let catalog_guard = self.catalog_manager.get_catalog_core_guard().await;
```
Comment (yezizp2012) [inline src/meta/src/stream/source_manager.rs:92]: Estimate affiliated source firstly could cover all cases of materialized source. This operation can avoid locking catalog.

**Review by yezizp2012 — APPROVED** [review]
LGTM

**Review by hzxa21 — APPROVED** [review]

File: src/meta/src/stream/source_manager.rs (hunk 1 above)
Comment (zbzbw) [reply src/meta/src/stream/source_manager.rs]: Refactored.
