### PR TITLE
fix(meta): fix stop all actors step of recovery

### LINKED ISSUE #4493: bug: create materialized view hang after meta restart
**Describe the bug**
1. create a table t1:
```sql
create table t1 (v1 int, v2 int);
```
2. restart meta.
3. create materialized view on t1:
```sql
create materialized view mvx as select max(v1) as max_v1 from t1;
```

When enabled recovery in meta, step 3 will hang, it seems like the table fragments have been inserted into meta store with state starting, but the ddl barrier is not completed.

**To Reproduce**
As title.

**Expected behavior**
Create mv success.

### PR DESCRIPTION
**Pull request by cnissnzg**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Use actors in handles rather than actor_info in stop_all_actors(), so we can do it successfully when doing recovery.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

Resolve #4493

### CODE REVIEW

File: src/stream/src/task/stream_manager.rs [hunk 1]
```diff
@@ -280,13 +280,7 @@ impl LocalStreamManager {
         let (actor_ids_to_send, actor_ids_to_collect) = {
             let core = self.core.lock();
             let actor_ids_to_send = core.context.lock_barrier_manager().all_senders();
-            let actor_ids_to_collect = core
-                .context
-                .actor_infos
```
Comment (BugenZhao) [inline src/stream/src/task/stream_manager.rs:285]: The actor infos are all actors **we know** from this compute node. It may include actors from other compute nodes.

**Review by BugenZhao — APPROVED** [review]

**Review by yezizp2012 — APPROVED** [review]
