### PR TITLE
fix(frontend): allow source as 1st arg in tumble/hop

### LINKED ISSUE #2758: tumble function will not bind sources on the table argument (its 1st arg)
**Describe the bug**

TUMBLE function has 3 arguments and its first argument will accept a relation. Technically, it should be an arbitrary relation including subquery (https://github.com/singularity-data/risingwave/issues/2733), source, table, and materialized view, but right now it only supports table/mv.

**To Reproduce**
Steps to reproduce the behavior.

```
create source ad_click (
    bid_id bigint,
    click_timestamp timestamp
) with (
    'connector' = 'kafka',
    'kafka.topic' = 'ad_click',
    'kafka.brokers' = '127.0.0.1:29092',
    'kafka.scan.startup.mode' = 'earliest'
) row format json;
```

```
dev=> create materialized view t as select * from tumble(ad_click, click_timestamp, interval '1' minute);
ERROR:  Catalog error: table not found: ad_click
```

**Expected behavior**

It should search source catalogs as well. 

**Additional context**

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

As title

## Checklist

- [x] I have written necessary docs and comments

## Refer to a related PR or issue link (optional)

Fix #2758

### CODE REVIEW

File: src/frontend/src/binder/relation/window_table_function.rs [hunk 1]
```diff
@@ -93,46 +93,17 @@ impl Binder {
...
 
-        let columns = table_catalog.columns().to_vec();
-        if columns.iter().any(|col| {
-            col.name().eq_ignore_ascii_case("window_start")
-                || col.name().eq_ignore_ascii_case("window_end")
-        }) {
-            return Err(ErrorCode::BindError(
-                "column names `window_start` and `window_end` are not allowed in window table function's input."
-                .into())
-            .into());
```
Comment (xxchan) [inline src/frontend/src/binder/relation/window_table_function.rs:110]: The error is removed?

**Review by xxchan — APPROVED** [review]
Others LGTM

File: src/frontend/src/binder/relation/window_table_function.rs (hunk 1 above)
Comment (neverchanje) [reply src/frontend/src/binder/relation/window_table_function.rs:110]: In fact the error here didn't make sense and I was going to raise an issue for that. Because that will mean we do not support tvf-on-tvf. 

For example, HOP(select * from tumble(t, report_time), window_end),

**Review by neverchanje — APPROVED** [review]
It'd be nice if there are some e2e tests here. For example like the tvf-on-tvf case I had commented.

File: src/frontend/src/binder/relation/window_table_function.rs (hunk 1 above)
Comment (xiangjinwu) [reply src/frontend/src/binder/relation/window_table_function.rs:110]: But how does the user specify which `window_start` column to use in this case?

Comment (TennyZhuang) [reply src/frontend/src/binder/relation/window_table_function.rs:110]: What’s the use case of TVF over TVF?

Comment (TennyZhuang) [reply src/frontend/src/binder/relation/window_table_function.rs:110]: Add check back now, since it's hard to handle the case.

**Review by xiangjinwu — APPROVED** [review]
