### PR TITLE
fix(frontend): check arguments for agg call

### LINKED ISSUE #2464: Proper error handling for aggregate functions
**Describe the bug**
After using `min` / `max` / `sum` / `avg` with invalid number of arguments, the database crashes.
```
noel=> select min(1); agg#0 
-------
     1
(1 row)

noel=> select min(1, 2);                                                                                                            
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

`count` emits an internal error:
```
noel=> select count(1,2);                                                                                                          
ERROR:  internal error: internal error: [PlanNode: Ok(SortAgg(SortAggNode { group_keys: [], agg_calls: [AggCall { r#type: Count, args: [Arg { input: Some(InputRefExpr { column_idx: 0 }), r#type: Some(DataType { type_name: Int32, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }) }, Arg { input: Some(InputRefExpr { column_idx: 1 }), r#type: Some(DataType { type_name: Int32, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }) }], return_type: Some(DataType { type_name: Int64, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), distinct: false }] }))] Failed to build executor: internal error: Agg with more than 1 input not supported.
```

**To Reproduce**
See above.

**Expected behavior**
Error message similar to other invalid expressions, e.g. for `substr`:
```
noel=> select substr(1,2,3)
noel-> ;
ERROR:  Feature is not yet implemented: Substr[Int32, Int32, Int32], Tracking issue: https://github.com/singularity-data/risingwave/issues/112
noel=> 
```

**Additional context**

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

## What's changed and what's your intention?

This PR distinguishes unsupported agg-calls from invalid ones and makes it not panic on invalid arguments.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
- Close #2464

### CODE REVIEW

File: src/frontend/src/expr/agg_call.rs [hunk 1]
```diff
@@ -68,32 +91,25 @@ impl AggCall {
                 DataType::Float32 => DataType::Float32,
                 DataType::Float64 => DataType::Float64,
                 DataType::Interval => DataType::Interval,
-                _ => return None,
+                _ => return unsupported(),
```
Comment (neverchanje) [inline src/frontend/src/expr/agg_call.rs:94]: avg ( smallint ) → numeric
avg ( integer ) → numeric
avg ( bigint ) → numeric
avg ( numeric ) → numeric
avg ( real ) → double precision
avg ( double precision ) → double precision
avg ( interval ) → interval
sum ( smallint ) → bigint
sum ( integer ) → bigint
sum ( bigint ) → numeric
sum ( numeric ) → numeric
sum ( real ) → real
sum ( double precision ) → double precision
sum ( interval ) → interval
sum ( money ) → money

https://www.postgresql.org/docs/current/functions-aggregate.html

```suggestion
                _ => return invalid(),
```

We have actually supported the full valid type list, so maybe we should use invalid?

Comment (BugenZhao) [reply src/frontend/src/expr/agg_call.rs:94]: Good catch! Will fix.

**Review by neverchanje — APPROVED** [review]
lgtm
