### PR TITLE
fix(array): inconsistent hash behavior of `Datum` and `Array::Item`

### LINKED ISSUE #3457: `Hash` implementation on `Datum` is not consistent with `Array::hash_at`
As long as we use `Datum` in a row, this affects the correctness of the consistent hash.

We use `Datum::hash` (`Option<ScalarImpl>::hash`) when hashing a row,
https://github.com/singularity-data/risingwave/blob/d577da0ce396438acd9455b7f07b6ad041038bc6/src/common/src/array/data_chunk_iter.rs#L292-L302

while using `Array::hash_at` when hashing an array or a data chunk.
https://github.com/singularity-data/risingwave/blob/d864f300132b41e6734c21f8ccfe5a7fd3cdb6b4/src/common/src/array/stream_chunk.rs#L229-L241

The behavior of these two implementations differs on...
- `Array::hash_at` manually hash `NULL` as `NULL_VAL_FOR_HASH`, while null datum is handled by `Option`.
https://github.com/singularity-data/risingwave/blob/36d4930ad060728562c96deb28acb5a186b0e982/src/common/src/array/mod.rs#L77-L78
- `Array::hash_at` may also behave differently from `ScalarImpl::hash`.

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title. This is a fix for common types except for array and struct. Check #3457 for more details.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- #3457

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

File: src/common/src/array/data_chunk_iter.rs [hunk 1]
```diff
@@ -296,29 +296,21 @@ impl Row {
...
         H: BuildHasher,
     {
         let mut hasher = hash_builder.build_hasher();
         for idx in hash_indices {
-            let datum = self.0.get(*idx);
-            match datum {
-                Some(datum) => datum.hash(&mut hasher),
-                None => bail!("index {} out of row bound", idx),
-            }
+            hash_datum(&self.0[*idx], &mut hasher);
```
Comment (xx01cyx) [inline src/common/src/array/data_chunk_iter.rs:311]: What if idx is greater than the length of the row? 🤔

Comment (BugenZhao) [reply src/common/src/array/data_chunk_iter.rs:311]: Indexing with `[..]` will panic if out of bound.

Comment (xx01cyx) [reply src/common/src/array/data_chunk_iter.rs:311]: Should we panic here? Or should we return an error?

Comment (BugenZhao) [reply src/common/src/array/data_chunk_iter.rs:311]: I think panicking here is okay since the indices are inferred or specified by some other components most of the time. If this fails, there must be a bug in our system and we're unable to recover it.

**Review by xx01cyx — APPROVED** [review]
