### PR TITLE
fix(batch): fix a bug of exchange and project.

### LINKED ISSUE #2486: bug: the implementation of BatchAgg might be wrong.
**Describe the bug**
I modified tpch q21 to only `select *`, and it outputs 15 rows, which is correct. But, when I modified it to `select count(*)`, it returns 0, which is absolutely wrong. BTW, `select count(s_name)` returns 15, which is correct.
Besides, I add `group by s_name` and `select count(s_name)` and it returns 609, which is incorrect.

**To Reproduce**
```
select
    count(*) 
from
    supplier,
    lineitem l1,
    orders,
    nation
where
    s_suppkey = l1.l_suppkey
    and o_orderkey = l1.l_orderkey
    and o_orderstatus = 'F'
    and l1.l_receiptdate > l1.l_commitdate
    and exists (
        select
            *
        from
            lineitem l2
        where
            l2.l_orderkey = l1.l_orderkey
            and l2.l_suppkey <> l1.l_suppkey
    )
    and not exists (
        select
            *
        from
            lineitem l3
        where
            l3.l_orderkey = l1.l_orderkey
            and l3.l_suppkey <> l1.l_suppkey
            and l3.l_receiptdate > l3.l_commitdate
    )
    and s_nationkey = n_nationkey
    and n_name = 'IRAQ';
```
You can change q21 to this to reproduce the bug.

**Expected behavior**
We expect `count(*)` to return 15.

**Additional context**
I think there are something wrong with the implementation of BatchAgg.

### PR DESCRIPTION
**Pull request by likg227**
## What's changed and what's your intention?

We'd better compact DataChunk first if we want to manipulate something in it. 
Project should consider the case that zero columns with non-zero cardinality.

## Refer to a related PR or issue link (optional)

close #2486

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM

**Comment by lmatz** [comment]
If it is local to the local hash shuffle, then originally by design, the data chunk is not compacted.

It seems now we require the data chunk is always compacted before being processed by any executor?

**Comment by likg227** [comment]
> If it is local to the local hash shuffle, then originally by design, the data chunk is not compacted.
> 
> It seems now we require the data chunk is always compacted before being processed by any executor?

Not sure about it, but if we want to directly use cardinality and columns in it, we should compact it first to avoid tricky bugs.

**Review by skyzh — COMMENTED** [review]
Should this logic be part of `GenericExchangeExecutor2`? HashShuffle is not the only sender.

**Comment by skyzh** [comment]
Okay, I get it, we only need to compact for remote channels.

File: src/batch/src/executor2/project.rs [hunk 1]
```diff
@@ -56,7 +56,11 @@ impl ProjectExecutor2 {
                 .iter_mut()
                 .map(|expr| expr.eval(&data_chunk).map(Column::new))
                 .collect::<Result<Vec<_>>>()?;
-            let ret = DataChunk::builder().columns(arrays).build();
+            let ret = if arrays.is_empty() {
+                DataChunk::new_dummy(data_chunk.cardinality())
+            } else {
+                DataChunk::builder().columns(arrays).build()
```
Comment (lmatz) [inline src/batch/src/executor2/project.rs:62]: If we have `.visibility()` when building this new data chunk, then we don't need the change in `HashShuffleSender`. Do I understand this correctly?

Comment (likg227) [reply src/batch/src/executor2/project.rs:62]: Actually, there are two bug fix in this pr, although there related to one issue.
The code you reference is to make Project deal with zero columns non-zero cardinality.

Comment (lmatz) [reply src/batch/src/executor2/project.rs:62]: I see, can we still let the executor instead of `ShuffleSender` decide whether to compact a data chunk? `BatchHashAgg` would produce incorrect results?

Comment (likg227) [reply src/batch/src/executor2/project.rs:62]: Actually it is the Exchange that produce incorrect results.
