### PR TITLE
fix(frontend): show distinct in agg

### LINKED ISSUE #2724: bug: should mark agg functions `distinct` or not in explain results
**Describe the bug**

```
eric=> explain select count(distinct l_partkey) from lineitem;
                       QUERY PLAN
---------------------------------------------------------
 BatchSimpleAgg { aggs: [count($0)] }
   BatchExchange { order: [], dist: Single }
     BatchScan { table: lineitem, columns: [l_partkey] }
```

**To Reproduce**

explain a distinct aggregation

**Expected behavior**

```diff
- BatchSimpleAgg { aggs: [count($0)] }
+ BatchSimpleAgg { aggs: [count(distinct $0)] }
```

**Additional context**

### PR DESCRIPTION
**Pull request by lmatz**
## What's changed and what's your intention?
As per the title.

## Checklist

~- [ ] I have written necessary docs and comments~
~- [ ] I have added necessary unit tests and integration tests~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
closes #2724

### CODE REVIEW

File: src/frontend/src/optimizer/plan_node/logical_agg.rs [hunk 1]
```diff
@@ -47,11 +47,23 @@ pub struct PlanAggCall {
...
+        write!(f, "{}", self.0)
+    }
+}
+
 impl fmt::Debug for PlanAggCall {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         let mut builder = f.debug_tuple(&format!("{}", self.agg_kind));
         self.inputs.iter().for_each(|child| {
-            builder.field(child);
+            let input_ref = InputRefWithDistinct(child, self.distinct);
```
Comment (lmatz) [inline src/frontend/src/optimizer/plan_node/logical_agg.rs:65]: Based on the fact that `distinct` is a variable independent of `inputRef` in `PlanAggCall`, we will not have the case that we have multiple input refs but only some of them is `distinct`?

Comment (xiangjinwu) [reply src/frontend/src/optimizer/plan_node/logical_agg.rs:65]: Yes, we do not [foresee](https://www.postgresql.org/docs/current/sql-expressions.html#:~:text=or%20distinct%20set%20of%20values%2C%20for%20multiple%20expressions) any agg call to be distinct only on part of its inputs.

However, when an agg call has multiple inputs (e.g. `string_agg`), it does not look well: `string_agg(distinct $0, distinct $1)`.

Alternatively we can use `string_agg-distinct($0, $1)`, or avoid `debug_tuple` and implement our own formatting to get `string_agg(distinct $0, $1)`.

Comment (lmatz) [reply src/frontend/src/optimizer/plan_node/logical_agg.rs]: I implemented our own formatting

**Review by xiangjinwu — APPROVED** [review]
