### PR TITLE
fix: make debezium work again 

### LINKED ISSUE #4694: Can not handle update and delete event in debezium source
**Describe the bug**
We use debezium as CDC source. When `delete` events come, it didn't work and the rows that should have been deleted still exist. Same things also happend in `update` events, old rows and new rows both exist.

**To Reproduce**

1. Build a debezium connect as in https://debezium.io/documentation/reference/stable/tutorial.html
2. Create Source
```sql
dev=> create materialized source s ( id integer , first_name varchar , last_name varchar , email varchar , PRIMARY KEY ( id ) ) with ( connector = 'kafka', topic = 'dbserver1.inventory.customers', properties.bootstrap.server = 'kafka:9092' ) row format debezium_json;
CREATE_SOURCE
dev=> select * from s;
  id  | first_name | last_name |         email         
------+------------+-----------+-----------------------
 1002 | George     | Bailey    | gbailey@foobar.com
 1001 | Sally      | Thomas    | sally.thomas@acme.com
 1003 | Edward     | Walker    | ed@walker.com
 1004 | Anne       | Kretchmar | annek@noanswer.org
(4 rows)
```
3. Update rows as in https://debezium.io/documentation/reference/stable/tutorial.html#updating-database-viewing-update-event
4. Query results and see both rows exist
```sql
dev=> select * from s;
  id  | first_name | last_name |         email         
------+------------+-----------+-----------------------
 1001 | Sally      | Thomas    | sally.thomas@acme.com
 1003 | Edward     | Walker    | ed@walker.com
 1004 | Anne       | Kretchmar | annek@noanswer.org
 1002 | George     | Bailey    | gbailey@foobar.com
 1004 | Anne Marie | Kretchmar | annek@noanswer.org
(5 rows)
```

**Expected behavior**
`update` and `delete` event should work expect as expected.

**Additional context**
We do not specific pk when create source, and we generate different pk when create and delete rows.

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

as title, make CDC source handle pk correctly

**known issue**: #0 column is always reserved for row_id, no matter pk is row_id or not. If pk is specified by user, row_id is kept in its position with NULL value. 

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

following #4722 
fix #4694

### CODE REVIEW

File: src/stream/src/executor/source/source_executor.rs [hunk 1]
```diff
@@ -156,6 +156,8 @@ impl<S: StateStore> SourceExecutor<S> {
     async fn refill_row_id_column(&mut self, chunk: StreamChunk, append_only: bool) -> StreamChunk {
         let row_id_index = self.source_desc.row_id_index;
         let row_id_column_id = self.source_desc.columns[row_id_index as usize].column_id;
+        let pk_column_ids = &self.source_desc.pk_column_ids;
+        let specified_pk = pk_column_ids != &vec![0];
```
Comment (BugenZhao) [inline src/stream/src/executor/source/source_executor.rs:160]: This looks too ad-hoc. 🥵🥵🥵 What if the pk columns are really `[0]`?

Comment (tabVersion) [reply src/stream/src/executor/source/source_executor.rs:160]: position 0 is reserved for row_id column and it is injected when registering source in meta. If user does not specify a pk, `pk_column_ids` will always be `[0]`

Comment (BugenZhao) [reply src/stream/src/executor/source/source_executor.rs:160]: Why don't we make `row_id_index` an `Option` for this?

https://github.com/singularity-data/risingwave/blob/b36f6febd0b7814a08e4afed9c0d43ee29446e41/src/source/src/manager.rs#L93-L95

Comment (BugenZhao) [reply src/stream/src/executor/source/source_executor.rs:160]: > position 0 is reserved for row_id column and it is injected when registering source in meta.

Is this documented somewhere in the code?

Comment (tabVersion) [reply src/stream/src/executor/source/source_executor.rs:160]: > > position 0 is reserved for row_id column and it is injected when registering source in meta.
> 
> Is this documented somewhere in the code?

I think it is not documented. you can see code here https://github.com/singularity-data/risingwave/blob/2ad42f78bb17a747a03713a4bfecae94ace3df9b/src/frontend/src/handler/create_table.rs#L54

column_id always starts at 1

File: src/source/src/manager.rs [hunk 2]
```diff
@@ -92,7 +92,8 @@ pub struct SourceDesc {
 
     // The column index of row ID. By default it's 0, which means the first column is row ID.
     // TODO: change to Option<usize> when pk supported in the future.
```
Comment (BugenZhao) [inline src/source/src/manager.rs:94]:
```suggestion
    // The column index of row ID. If the primary key is specified by users, this will be `None`.
```

File: src/source/src/manager.rs [hunk 3]
```diff
@@ -147,7 +148,12 @@ impl SourceManager for MemSourceManager {
             "expected row_id_index >= 0, got {}",
             info.row_id_index
         );
-        let row_id_index = info.row_id_index as usize;
+        let row_id_index = if info.pk_column_ids != vec![0] {
+            None
+        } else {
+            Some(0)
+        };
```
Comment (BugenZhao) [inline src/source/src/manager.rs:155]: So we're going to ignore the `info.row_id_index`? I think this should be decided in the frontend.

**Review by BugenZhao — COMMENTED** [review]
Rest LGTM

File: src/source/src/manager.rs (hunk 3 above)
Comment (tabVersion) [reply src/source/src/manager.rs:155]: Frontend will do it later. @xiangjinwu says there may be some compatible issues.

Comment (xiangjinwu) [reply src/source/src/manager.rs:155]: We can keep this implementation and make it work first, and then update `row_id_index` in proto as optional so that it is decided on frontend rather than handled here.

**Review by BugenZhao — APPROVED** [review]

**Comment by BugenZhao** [comment]
LGTM! Could you please also add some e2e tests for cdc source after this PR?

**Comment by tabVersion** [comment]
> LGTM! Could you please also add some e2e tests for cdc source after this PR?

Sure! I am reading ci/script and designing tests

**Comment by tabVersion** [comment]
@mergifyio requeue
