### PR TITLE
fix(executor): handle invalid `hop` arguments

### LINKED ISSUE #4504: better error message for `hop(t, col, INTERVAL '1', INTERVAL '0')`
**Describe the bug**

```
Reason:
db error: ERROR: ExecuteError: internal error: Invalid Parameter Value: Invalid parameter window: window_size 00:00:00 cannot be divided by window_slide 00:00:01.
', src/tests/sqlsmith/src/bin/main.rs:175:13
```

For those not familiar with semantics of `hop`, this error message is confusing, since it seems to state that `0` cannot be divided by `1`.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
1. State that window-size must be non-zero, otherwise we would be unable to `slide` the window forward.
2. ~~OR permit 0 divided by 1, if this is valid by semantics of `hop`.~~ Should prevent user from doing this.

**Additional context**

Related: https://github.com/singularity-data/risingwave/issues/3966

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Handle non-positive `window_size` and `window_slide` args.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### Types of user-facing changes

* SQL commands, functions, and operators

### Release note

Updates user error message, prevents some edge cases from occurring.

Before (cr @xxchan : https://github.com/singularity-data/risingwave/issues/4504#issuecomment-1208473049):
```
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:01 cannot be divided by window_slide 00:00:-1.
dev=> select * from hop(t, x, INTERVAL '1', INTERVAL '-1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:-1 cannot be divided by window_slide 00:00:01.
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '-1');
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?>
```

After:
```
dev=> create table t(x timestamp);
CREATE_TABLE
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:01 and window_slide 00:00:-1 must be positive.
dev=> select * from hop(t, x, INTERVAL '1', INTERVAL '-1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:-1 and window_slide 00:00:01 must be positive.
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '-1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:-1 and window_slide 00:00:-1 must be positive.
```

## Refer to a related PR or issue link (optional)

closes #4504

### CODE REVIEW

File: src/stream/src/executor/hop_window.rs [hunk 1]
```diff
@@ -87,6 +87,18 @@ impl HopWindowExecutor {
...
+        if !window_size.is_positive() || !window_slide.is_positive() {
+            return Err(ExprError::InvalidParam {
+                name: "window",
+                reason: format!(
+                    "window_size {} and window_slide {} must be positive",
+                    window_size, window_slide
+                ),
+            }
+            .into());
+        }
```
Comment (neverchanje) [inline src/stream/src/executor/hop_window.rs:100]: Is it duplicate with the param check in planner?

Comment (kwannoel) [reply src/stream/src/executor/hop_window.rs:100]: This is intentional, my thinking is that in the future if `window_size` / `window_slide` can be columns, this will only be able to be caught during runtime (i.e. in the executor) and not during planner phase.. Hence I added a check here as well.

If both `window_size` and `window_slide` are always literals, this check can be removed.

Comment (kwannoel) [reply src/stream/src/executor/hop_window.rs]: It doesn't make sense for window_size / window_slide to be dynamic. Will remove this check.

Comment (neverchanje) [reply src/stream/src/executor/hop_window.rs]: Yeah we have validated that they must be literals.

**Review by neverchanje — APPROVED** [review]
LGTM
