### PR TITLE
fix(expr): bool has different output format and cast-string format

### LINKED ISSUE #3146: boolean in `concat` should be formatted to `t f` instead of `true false`
**Describe the bug**
```
dev=> select true as col;
 col 
-----
 t
(1 row)

dev=> select true::varchar as col;
 col  
------
 true
(1 row)

dev=> select concat(true) as col;
 col  
------
 true
(1 row)
```

```
postgres=# select true as col;
 col 
-----
 t
(1 row)

postgres=# select true::varchar as col;
 col  
------
 true
(1 row)

postgres=# select concat(true) as col;
 col 
-----
 t
(1 row)
```

**To Reproduce**
As above.

**Expected behavior**
The same behavior with postgres.

### PR DESCRIPTION
**Pull request by xiangjinwu**
## What's changed and what's your intention?

Fixes #3146 by introducing a dedicated `BoolOut` expr. All other types can share the same expr/func for **I/O** and **from/to-string cast**.

Check doc comment of `cast_output` for details. The 2 different implementations in PostgreSQL are called `boolout` and `booltext`.

In PostgreSQL, only 4 types have cast-to-string different from output format: `bool`, `cidr`, `inet`, `xml`, and only 1 type has cast-from-string different from input format: `xml`.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

File: src/frontend/src/expr/mod.rs [hunk 1]
```diff
@@ -120,6 +120,23 @@ impl ExprImpl {
...
+    /// All other types have the same behavior when formatting to output and casting to string.
+    ///
+    /// References in `PostgreSQL`:
+    /// * [cast](https://github.com/postgres/postgres/blob/a3ff08e0b08dbfeb777ccfa8f13ebaa95d064c04/src/include/catalog/pg_cast.dat#L437-L444)
+    /// * [impl](https://github.com/postgres/postgres/blob/27b77ecf9f4d5be211900eda54d8155ada50d696/src/backend/utils/adt/bool.c#L204-L209)
+    pub fn cast_output(self) -> Result<ExprImpl> {
+        if self.return_type() == DataType::Boolean {
+            return Ok(FunctionCall::new(ExprType::BoolOut, vec![self])?.into());
+        }
+        self.cast_assign(DataType::Varchar)
```
Comment (kwannoel) [inline src/frontend/src/expr/mod.rs:138]: Why do we use `cast_assign` instead of `cast_explicit` here?

**Review by kwannoel — APPROVED** [review]

File: src/frontend/src/expr/mod.rs (hunk 1 above)
Comment (xiangjinwu) [reply src/frontend/src/expr/mod.rs:138]: Given the target is hard-coded to `Varchar`, both `assign` and `explicit` would allow the cast. There is no difference, as the error checking inside always pass.
