### PR TITLE
fix(batch): fix order_by with struct table

### LINKED ISSUE #3780: Bug(batch): panic when order by a table which has struct column
**Describe the bug**

```
2022-07-11T11:42:04.834594Z ERROR risingwave_batch::task::task_execution: Execution failed [TaskId { task_id: 1, stage_id: 1, query_id: "6393716a-d564-4512-9a0c-7caf5803ff55" }]: BatchError: Internal(Unmatched array and array builder types

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/std/src/backtrace.rs:328:13
   3: anyhow::error::<impl anyhow::Error>::msg
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.58/src/error.rs:81:36
   4: anyhow::private::format_err
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.58/src/lib.rs:665:13
   5: risingwave_batch::executor::order_by::OrderByExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/order_by.rs:240:29
   6: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
```

**To Reproduce**
Steps to reproduce:

```
create table st (v1 int, v2 struct<v3 int, v4 struct<v5 int, v6 int>>);
insert into st values(4,(3,(2, 2)));
insert into st values(1,(2,(1, 0)));
insert into st values(2,(5,(4, 1)));
insert into st values(1,(6,(3, 4)));
select * from st order by v1;
```

**Expected behavior**
Display the correct query result.

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Fix panic on batch query when doing order_by with struct table

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #3780

### CODE REVIEW

File: src/batch/src/executor/order_by.rs [hunk 1]
```diff
@@ -252,7 +252,8 @@ impl OrderByExecutor {
                             Interval,
                             NaiveDate,
                             NaiveTime,
-                            NaiveDateTime
+                            NaiveDateTime,
+                            Struct
```
Comment (xiangjinwu) [inline src/batch/src/executor/order_by.rs:256]: Seems `List` has similar issue.

Comment (StrikeW) [reply src/batch/src/executor/order_by.rs:256]: It would better to have a tool that can enumerate all cases. Seems we are working on sqlsmith to do the job.
