### PR TITLE
fix(metrics): fix iterator metrics data report duplication and lost

### LINKED ISSUE #4706: block cache data cache metrics abnormal
**Describe the bug**

During benchmarking with tpc-h and nexmark, the block cache data cache metrics rate is abnormally low (even zero). But data cache is actually accessed, we can check it by printing log in `get`. I guess some local metrics is not collected or reported.

image

image

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

In #2709 we introduced local metrics for iterators and block cache, which, however, needs to be carefully reported by caller. Besides, it didn't check if the its data is reported or reported multiple times. And that leads to abnormal metrics:

e.g. 70k+ meta cache access but 0 data cache accesss
image

After investigation, both metrics lost and metrics reported multiple times problems exist by:

```rust
#[derive(Default)]
pub struct StoreLocalStatistic {
    // ... ...

    reported: AtomicBool,
    added: AtomicBool,
}

impl StoreLocalStatistic {
    pub fn add(&mut self, other: &StoreLocalStatistic) {
        // ... ...

        if other.added.fetch_or(true, Ordering::SeqCst) {
            panic!("double added");
        }
    }

    pub fn report(&self, metrics: &StateStoreMetrics) {
        // ... ...

        if self.reported.fetch_or(true, Ordering::SeqCst) {
            panic!("double reported");
        }
    }
}

impl Drop for StoreLocalStatistic {
    fn drop(&mut self) {
        if !self.reported.load(Ordering::SeqCst) && !self.added.load(Ordering::SeqCst) {
            panic!("local stats lost!");
        }
    }
}
```

And with the check (not included in this PR, because it will break unit tests), I fixed all related bugs. Now the metrics looks fine:

image (3)

## TODO (but not in this PR):
This PR is just a quick fix of #2709 , without the checking code, the local metrics still need to be carefully handled. I think we should refactor it later.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
fix #4706

### CODE REVIEW

**Review by Li0k — APPROVED** [review]
LGTM, Thanks for this PR

**Review by hzxa21 — APPROVED** [review]

File: src/storage/src/hummock/iterator/merge_inner.rs [hunk 1]
```diff
@@ -327,8 +355,10 @@ where
 
 impl<I: HummockIterator, NE: NodeExtraOrderInfo> Drop for MergeIteratorInner<I, NE> {
     fn drop(&mut self) {
-        let mut stats = StoreLocalStatistic::default();
-        self.collect_local_statistic_impl(&mut stats);
-        stats.report(self.stats.as_ref());
+        if let Some(stats) = &self.stats {
```
Comment (wenym1) [inline src/storage/src/hummock/iterator/merge_inner.rs:358]: Why do we need to report metrics when `MergeIterator` drops?

Comment (MrCroxx) [reply src/storage/src/hummock/iterator/merge_inner.rs:358]: `MergeIterator` is the top level iterator for compactors.

File: src/storage/src/hummock/iterator/merge_inner.rs [hunk 2]
```diff
@@ -144,7 +158,21 @@ pub type UnorderedMergeIteratorInner<I: HummockIterator> =
     MergeIteratorInner<I, UnorderedNodeExtra>;
 
 impl<I: HummockIterator> UnorderedMergeIteratorInner<I> {
-    pub fn new(iterators: impl IntoIterator<Item = I>, stats: Arc<StateStoreMetrics>) -> Self {
+    pub fn new(iterators: impl IntoIterator<Item = I>) -> Self {
+        Self::create(iterators, None)
+    }
+
+    pub fn for_compactor(
```
Comment (wenym1) [inline src/storage/src/hummock/iterator/merge_inner.rs:165]: Instead of forcing all `HummockIterator` of `Compactor` to pass in a global stats, we may force compactor to collect the metrics of `HummockIterator` and report it.

File: src/storage/src/hummock/iterator/merge_inner.rs (hunk 1 above)
Comment (MrCroxx) [reply src/storage/src/hummock/iterator/merge_inner.rs:358]: I think the interface is still not friendly. I think refactor is needed after the fix.

**Comment by MrCroxx** [comment]
Discussed offline with @wenym1 , we decided to merge this PR first and refactor it later.
