### PR TITLE
fix(optimizer): predicate pushdown when there's no filter above join

### LINKED ISSUE #2463: frontend: predicate push-down doesn't work
In the following plan, `BatchFilter { predicate: ($1 < 10:Int32) }` should be transposed through Join

```sql
create table t1 (v1 int not null, v2 int not null);
create table t2 (v1 int not null, v2 int not null);
```

```
eric=> explain select t1.v2 as t1_v2, t2.v2 as t2_v2 from t1 join t2 on t1.v1 = t2.v1 and t1.v2 < 10;
                           QUERY PLAN
----------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchProject { exprs: [$1, $3], expr_alias: [t1_v2, t2_v2] }
     BatchFilter { predicate: ($1 < 10:Int32) }
       BatchHashJoin { type: Inner, predicate: $0 = $2 }
         BatchExchange { order: [], dist: HashShard([0]) }
           BatchScan { table: t1, columns: [v1, v2] }
         BatchExchange { order: [], dist: HashShard([0]) }
           BatchScan { table: t2, columns: [v1, v2] }
```

### PR DESCRIPTION
**Pull request by xxchan**
## What's changed and what's your intention?

as title
## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
close #2463

### CODE REVIEW

File: src/frontend/src/optimizer/rule/filter_join.rs [hunk 1]
```diff
@@ -47,17 +47,25 @@ pub struct FilterJoinRule {}
...
+        let (filter_predicate, join) = match plan.as_logical_filter() {
+            Some(filter) => {
+                let input = filter.input();
+                let join = input.as_logical_join()?;
+                (filter.predicate().clone(), join.clone())
+            }
+            None => {
+                let join = plan.as_logical_join()?;
+                (Condition::true_cond(), join.clone())
+            }
```
Comment (fuyufjh) [inline src/frontend/src/optimizer/rule/filter_join.rs:59]: This is quite tricky. Can you add some comments and/or rustdoc for it? :)

**Review by fuyufjh — APPROVED** [review]
