### PR TITLE
fix(optimizer): ApplyValues.

### LINKED ISSUE #4311: a nested query in SELECT makes the server panic
```sql
create table t1 (a int, b int);
create table t2 (b int, c int);
select a, (select t1.a), c from t1, t2 where t1.b = t2.b order by c;
```

**Expected behavior**
The server should not panic and the user should get an error message.

**Additional context**
```
thread 'tokio-runtime-worker' panicked at 'LogicalApply should be unnested', src/frontend/src/optimizer/plan_node/logical_apply.rs:183:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

cc @likg227

### PR DESCRIPTION
**Pull request by likg227**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
When Apply's left is Values, we should treat it like Scan.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #4311

### CODE REVIEW

File: src/frontend/src/optimizer/rule/apply_scan.rs [hunk 1]
```diff
@@ -33,7 +33,11 @@ impl Rule for ApplyScanRule {
 
         // LogicalJoin with correlated inputs in join condition has been handled by ApplyJoin. This
         // handles the ones without correlation
-        if let (None, None) = (right.as_logical_scan(), right.as_logical_join()) {
+        if let (None, None, None) = (
+            right.as_logical_scan(),
+            right.as_logical_join(),
+            right.as_logical_values(),
```
Comment (xiangjinwu) [inline src/frontend/src/optimizer/rule/apply_scan.rs:39]: To be fully correct, the exprs in `values` should not contain correlated input refs. Just raising awareness of this rather than suggesting an immediate fix, as we do not consider correlation in `values` at binding phase either:

https://github.com/singularity-data/risingwave/blob/3b84c1653d99c0a31b3326b7dca71d474cf9decc/src/frontend/src/binder/set_expr.rs#L40-L57

In the future, ApplyValues may look closer to ApplyProj rather than ApplyScan.

**Review by xiangjinwu — APPROVED** [review]

File: src/frontend/src/optimizer/rule/apply_scan.rs (hunk 1 above)
Comment (likg227) [reply src/frontend/src/optimizer/rule/apply_scan.rs:39]: So we should report error in binder when BoundValues has `correlated_input_refs`?
