### PR TITLE
fix(batch): Add handling of null values in build side key columns for Lookup Join

### LINKED ISSUE #4219: Panic occurs in Lookup Join when build side key columns has null values
**Describe the bug**
If the build side table has any null values on the key columns of the join predicate, a panic occurs.

**Expected behavior**
No panic should occur, and any rows with should not have any matches on the probe side table.

### PR DESCRIPTION
**Pull request by Graphcalibur**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
   - Lookup Join now handles null values in the build side key columns
   - Rows with null values in these columns will not have any match on the probe side table.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
Fixes #4219

### CODE REVIEW

File: src/batch/src/executor/join/lookup_join.rs [hunk 1]
```diff
@@ -313,7 +341,9 @@ impl<P: 'static + ProbeSideSourceBuilder> LookupJoinExecutor<P> {
 
             self.probe_side_source.reset();
             for row_key in &row_keys {
-                self.probe_side_source.add_scan_range(row_key)?;
+                if row_key.iter().all(|datum| datum.is_some()) {
+                    self.probe_side_source.add_scan_range(row_key)?;
```
Comment (lmatz) [inline src/batch/src/executor/join/lookup_join.rs:345]: Correct me if I am wrong,
if there is no `add_scan_range` that gets called here, we can just move on to the next loop. Then we don't need a `DummyExecutor`?

**Review by lmatz — APPROVED** [review]

File: src/batch/src/executor/join/lookup_join.rs (hunk 1 above)
Comment (Graphcalibur) [reply src/batch/src/executor/join/lookup_join.rs:345]: If the join is left outer join or left anti join, then we still need to add the row into the final join result. By using a `DummyExecutor`, we can reuse the existing join logic to handle this instead of making a special case for it.
