### PR TITLE
fix(frontend): create mview on singleton upstream mview

### LINKED ISSUE #4067: cannot create MV over simple agg MV
**Describe the bug**

```
create table t1(v1 int);
create materialized view mv1 as select sum(v1) as sum_v1 from t1;
create materialized view mv2 as select * from mv1;
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR fixes that we cannot create an mview on a singleton upstream mview. There're several reasons.
- `StreamTableScan` does not check whether the distribution key of upstream mview is empty, and always use `HashShard` distribution.
- If there's no exchange in the stream graph of new mview, we'll use the default `is_singleton = false` regardless of the distribution.
- The scheduler currently assume that the downstream chain actors lie on the same parallel unit of the upstream materializes, which makes it fail to resolve the upstream actor id of singleton mview.
- We won't broadcast the downstream chain actor infos to the upstream worker. When it creates a `Output`, it needs the downstream address to decide whether we need a `RemoteOutput`.

This PR also includes some style refinement of the stream manager. 💦

image

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Fix #4067

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM

File: src/frontend/src/optimizer/plan_node/batch_seq_scan.rs [hunk 1]
```diff
@@ -78,6 +79,11 @@ impl BatchSeqScan {
                 Distribution::Single
             } else {
                 match self.logical.distribution_key() {
+                    // FIXME: Should be `Single` if no distribution key.
```
Comment (BugenZhao) [inline src/frontend/src/optimizer/plan_node/batch_seq_scan.rs:82]: Opened #4164 for this.

File: proto/stream_plan.proto [hunk 2]
```diff
@@ -259,6 +259,10 @@ message ChainNode {
   bool disable_rearrange = 4;
   // Whether to place this chain on the same worker node as upstream actors.
   bool same_worker_node = 5;
+  // Whether the upstream materialize is and this chain should be a singleton.
+  // FIXME: This is a workaround for fragmenter since the distribution info will be lost if there's only one
+  // fragment in the downstream mview. Remove this when we refactor the fragmenter.
+  bool is_singleton = 6;
```
Comment (BowenXiao1999) [inline proto/stream_plan.proto:265]: What is the desired way?

File: src/frontend/src/stream_fragmenter/graph/fragment_graph.rs [hunk 3]
```diff
@@ -62,6 +62,7 @@ impl StreamFragment {
         Self {
             fragment_id,
             fragment_type: FragmentType::Others,
+            // FIXME: is it okay to use `false` as default value?
             is_singleton: false,
```
Comment (BowenXiao1999) [inline src/frontend/src/stream_fragmenter/graph/fragment_graph.rs:66]: Will it be re-write?

File: src/frontend/src/optimizer/property/distribution.rs [hunk 4]
```diff
@@ -101,10 +101,16 @@ impl Distribution {
...
                 Distribution::Single => None,
-                Distribution::HashShard(key) => Some(DistributionProst::HashInfo(HashInfo {
-                    output_count,
-                    key: key.iter().map(|num| *num as u32).collect(),
-                })),
+                Distribution::HashShard(key) => {
+                    assert!(
+                        !key.is_empty(),
+                        "hash key should not be empty, use `Single` instead"
+                    );
```
Comment (BugenZhao) [inline src/frontend/src/optimizer/property/distribution.rs:108]: Opened #4165 for this.

File: src/frontend/src/stream_fragmenter/mod.rs [hunk 5]
```diff
@@ -196,11 +196,13 @@ impl StreamFragmenter {
...
             NodeBody::TopN(_) => current_fragment.is_singleton = true,
 
-            NodeBody::Chain(ref node) => {
+            // FIXME: workaround for single-fragment mview on singleton upstream mview.
+            NodeBody::Chain(node) => {
                 // memorize table id for later use
                 state
                     .dependent_table_ids
                     .insert(TableId::new(node.table_id));
+                current_fragment.is_singleton = node.is_singleton;
```
Comment (BowenXiao1999) [inline src/frontend/src/stream_fragmenter/mod.rs:205]: IIUC, the flag `node.is_singleton` for chain_node is alwasy true? Or it depends on the whether the upstream mview is singleton or not.

File: src/meta/src/rpc/service/ddl_service.rs [hunk 6]
```diff
@@ -467,6 +467,7 @@ where
         for fragment in fragment_graph.fragments.values_mut() {
             mview_count += fill_mview_id(fragment.node.as_mut().unwrap(), mview_id);
         }
+        let fragment_graph = fragment_graph;
```
Comment (BowenXiao1999) [inline src/meta/src/rpc/service/ddl_service.rs:470]:
```suggestion
```

**Review by BowenXiao1999 — APPROVED** [review]
LGTM

File: src/frontend/src/stream_fragmenter/graph/fragment_graph.rs (hunk 3 above)
Comment (BowenXiao1999) [reply src/frontend/src/stream_fragmenter/graph/fragment_graph.rs:66]: Found it below.

File: src/frontend/src/stream_fragmenter/mod.rs (hunk 5 above)
Comment (BugenZhao) [reply src/frontend/src/stream_fragmenter/mod.rs:205]: > Or it depends on the whether the upstream mview is singleton or not.

✔️

File: src/meta/src/rpc/service/ddl_service.rs (hunk 6 above)
Comment (BugenZhao) [reply src/meta/src/rpc/service/ddl_service.rs:470]: This's for making it immutable, so we won't fear that the variable will unexpectedly change after this line. 🥺

File: proto/stream_plan.proto (hunk 2 above)
Comment (BugenZhao) [reply proto/stream_plan.proto:265]: We may directly operate on the `Fragment` struct in the frontend instead of the protobuf struct, so that we may be able to directly find whether a fragment is a singleton or not instead of checking the dispatcher type.

Currently, we cannot check whether `is_singleton` for the most upstream fragment since there's no exchange before it. That's why we need hacking for `TopN` and `Chain`. 😢
